# Generated by Django 4.2.20 on 2025-04-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0003_eldlog_odometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eldlog',
            old_name='location_name',
            new_name='address',
        ),
    ]
